[pytest]
testpaths = ui_tests api_tests
addopts = --tb=short --no-header -v --junit-xml=results/results.xml
console_output_style = count
markers =
    ui: UI automation tests
    api: API automation tests
